package com.rohit.inventory.service;
import com.rohit.inventory.dto.request.*; import com.rohit.inventory.dto.response.UserResponse; import com.rohit.inventory.entity.*; import com.rohit.inventory.exception.*; import com.rohit.inventory.mapper.UserMapper; import com.rohit.inventory.repository.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class UserService { private final UserRepository users; private final RoleRepository roles; private final WarehouseRepository warehouses; private final PasswordEncoder encoder; private final UserMapper mapper; private final AuditService audit; public UserService(UserRepository users,RoleRepository roles,WarehouseRepository warehouses,PasswordEncoder encoder,UserMapper mapper,AuditService audit){this.users=users;this.roles=roles;this.warehouses=warehouses;this.encoder=encoder;this.mapper=mapper;this.audit=audit;}
 @Transactional(readOnly=true) public Page<UserResponse> list(String search,UserStatus status,String role,Pageable pageable){return users.search(blankToNull(search),status,blankToNull(role),pageable).map(mapper::toResponse);} @Transactional(readOnly=true) public UserResponse get(UUID id){return mapper.toResponse(find(id));}
 @Transactional(readOnly=true) public UUID idForEmail(String email){return users.findByEmail(email).orElseThrow(()->new ResourceNotFoundException("User not found")).getId();}
 @Transactional public UserResponse create(CreateUserRequest r,UUID actor){ if(users.existsByEmail(r.email().toLowerCase()))throw new DuplicateResourceException("Email is already in use"); if(users.findByUsername(r.username()).isPresent())throw new DuplicateResourceException("Username is already in use"); User u=new User(); u.setUsername(r.username());u.setEmail(r.email().toLowerCase());u.setPasswordHash(encoder.encode(r.password()));u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setPhone(r.phone());u.setRoles(resolveRoles(r.roleCodes()));u.setAssignedWarehouses(resolveWarehouses(r.warehouseIds())); users.save(u); audit.record(actor,"USER_CREATED","USER",u.getId(),Map.of("email",u.getEmail(),"roles",r.roleCodes()));return mapper.toResponse(u); }
 @Transactional public UserResponse update(UUID id,UpdateUserRequest r,UUID actor){User u=find(id);if(users.existsByEmailAndIdNot(r.email().toLowerCase(),id))throw new DuplicateResourceException("Email is already in use");u.setEmail(r.email().toLowerCase());u.setFirstName(r.firstName());u.setLastName(r.lastName());u.setPhone(r.phone());audit.record(actor,"USER_UPDATED","USER",id,Map.of("email",u.getEmail()));return mapper.toResponse(u);}
 @Transactional public UserResponse status(UUID id,UpdateUserStatusRequest r,UUID actor){User u=find(id);u.setStatus(r.status());audit.record(actor,r.status()==UserStatus.ACTIVE?"USER_ACTIVATED":"USER_DEACTIVATED","USER",id,Map.of("status",r.status().name()));return mapper.toResponse(u);}
 @Transactional public UserResponse roles(UUID id,AssignRolesRequest r,UUID actor){User u=find(id);u.setRoles(resolveRoles(r.roleCodes()));audit.record(actor,"ROLE_ASSIGNMENT_CHANGED","USER",id,Map.of("roles",r.roleCodes()));return mapper.toResponse(u);}
 private User find(UUID id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found"));} private Set<Role> resolveRoles(Set<String> codes){Set<Role> result=new HashSet<>();for(String code:codes)result.add(roles.findByCode(code).orElseThrow(()->new ResourceNotFoundException("Role not found: "+code)));return result;} private Set<Warehouse> resolveWarehouses(Set<UUID> ids){if(ids==null)return new HashSet<>();Set<Warehouse> result=new HashSet<>();for(UUID id:ids)result.add(warehouses.findById(id).orElseThrow(()->new ResourceNotFoundException("Warehouse not found: "+id)));return result;} private String blankToNull(String s){return s==null||s.isBlank()?null:s;}
}
