CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(120) NOT NULL, description TEXT, is_system BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE permissions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(120) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, module VARCHAR(80) NOT NULL, description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), username VARCHAR(80) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(30), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','LOCKED')), last_login_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_roles (user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, role_id));
CREATE TABLE role_permissions (role_id UUID NOT NULL REFERENCES roles(id) ON DELETE RESTRICT, permission_id UUID NOT NULL REFERENCES permissions(id) ON DELETE RESTRICT, PRIMARY KEY(role_id, permission_id));

CREATE TABLE warehouses (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(150) NOT NULL, address_line1 VARCHAR(255), address_line2 VARCHAR(255), city VARCHAR(100), state VARCHAR(100), country VARCHAR(100) NOT NULL DEFAULT 'India', postal_code VARCHAR(20), capacity_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (capacity_quantity >= 0), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','MAINTENANCE')), manager_user_id UUID REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE user_warehouses (user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id, warehouse_id));
CREATE TABLE warehouse_zones (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, code VARCHAR(40) NOT NULL, name VARCHAR(120) NOT NULL, zone_type VARCHAR(30) NOT NULL DEFAULT 'STORAGE' CHECK (zone_type IN ('STORAGE','RECEIVING','DISPATCH','QUARANTINE','DAMAGED','COLD_STORAGE','OTHER')), capacity_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK (capacity_quantity >= 0), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE','MAINTENANCE')), layout_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(warehouse_id,code), UNIQUE(id,warehouse_id));
CREATE TABLE warehouse_layouts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, version INTEGER NOT NULL CHECK(version > 0), layout_name VARCHAR(150) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','ACTIVE','ARCHIVED')), layout_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, created_by UUID REFERENCES users(id) ON DELETE SET NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(warehouse_id, version));
CREATE TABLE warehouse_layout_elements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), layout_id UUID NOT NULL REFERENCES warehouse_layouts(id) ON DELETE RESTRICT, zone_id UUID REFERENCES warehouse_zones(id) ON DELETE RESTRICT, element_type VARCHAR(30) NOT NULL CHECK(element_type IN ('ZONE','RACK','AISLE','SHELF_GROUP','RECEIVING_GATE','DISPATCH_GATE','QUARANTINE_AREA','DAMAGED_AREA','LABEL')), element_code VARCHAR(60) NOT NULL, label VARCHAR(150), position_x NUMERIC(12,3) NOT NULL DEFAULT 0, position_y NUMERIC(12,3) NOT NULL DEFAULT 0, position_z NUMERIC(12,3) NOT NULL DEFAULT 0, rotation_x NUMERIC(12,3) NOT NULL DEFAULT 0, rotation_y NUMERIC(12,3) NOT NULL DEFAULT 0, rotation_z NUMERIC(12,3) NOT NULL DEFAULT 0, scale_x NUMERIC(12,3) NOT NULL DEFAULT 1 CHECK(scale_x > 0), scale_y NUMERIC(12,3) NOT NULL DEFAULT 1 CHECK(scale_y > 0), scale_z NUMERIC(12,3) NOT NULL DEFAULT 1 CHECK(scale_z > 0), capacity_override NUMERIC(18,3) CHECK(capacity_override >= 0), visual_metadata JSONB NOT NULL DEFAULT '{}'::jsonb, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(layout_id,element_code));

CREATE TABLE categories (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(120) NOT NULL, description TEXT, parent_category_id UUID REFERENCES categories(id) ON DELETE SET NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX ux_categories_root_name ON categories(name) WHERE parent_category_id IS NULL;
CREATE UNIQUE INDEX ux_categories_child_name ON categories(parent_category_id,name) WHERE parent_category_id IS NOT NULL;
CREATE TABLE suppliers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), code VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, contact_name VARCHAR(150), email VARCHAR(255), phone VARCHAR(30), address_line1 VARCHAR(255), city VARCHAR(100), state VARCHAR(100), country VARCHAR(100), postal_code VARCHAR(20), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), sku VARCHAR(80) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, description TEXT, barcode VARCHAR(120) UNIQUE, category_id UUID NOT NULL REFERENCES categories(id) ON DELETE RESTRICT, unit_of_measure VARCHAR(20) NOT NULL DEFAULT 'UNIT', cost_price NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK(cost_price >= 0), selling_price NUMERIC(19,4) NOT NULL DEFAULT 0 CHECK(selling_price >= 0), minimum_stock NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(minimum_stock >= 0), reorder_level NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(reorder_level >= 0), maximum_stock NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(maximum_stock >= 0), weight_kg NUMERIC(12,3) CHECK(weight_kg >= 0), length_cm NUMERIC(12,2) CHECK(length_cm >= 0), width_cm NUMERIC(12,2) CHECK(width_cm >= 0), height_cm NUMERIC(12,2) CHECK(height_cm >= 0), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK(maximum_stock = 0 OR maximum_stock >= reorder_level), CHECK(reorder_level >= minimum_stock));
CREATE TABLE product_suppliers (product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, supplier_id UUID NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT, supplier_sku VARCHAR(100), is_preferred BOOLEAN NOT NULL DEFAULT FALSE, lead_time_days INTEGER CHECK(lead_time_days >= 0), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','INACTIVE')), PRIMARY KEY(product_id,supplier_id));

CREATE TABLE inventory (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, zone_id UUID NOT NULL, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, on_hand_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(on_hand_quantity >= 0), reserved_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(reserved_quantity >= 0), damaged_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(damaged_quantity >= 0), available_quantity NUMERIC(18,3) GENERATED ALWAYS AS (on_hand_quantity-reserved_quantity) STORED, version BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(zone_id,warehouse_id) REFERENCES warehouse_zones(id,warehouse_id) ON DELETE RESTRICT, UNIQUE(warehouse_id,zone_id,product_id), CHECK(reserved_quantity <= on_hand_quantity));
CREATE TABLE stock_transfers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), transfer_number VARCHAR(50) NOT NULL UNIQUE, source_warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, destination_warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, status VARCHAR(25) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PENDING','APPROVED','PICKED','IN_TRANSIT','RECEIVED','COMPLETED','REJECTED','CANCELLED','FAILED')), requested_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, approved_at TIMESTAMPTZ, dispatched_at TIMESTAMPTZ, received_at TIMESTAMPTZ, completed_at TIMESTAMPTZ, remarks TEXT, cancellation_reason TEXT, failure_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK(source_warehouse_id <> destination_warehouse_id));
CREATE TABLE stock_transfer_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), stock_transfer_id UUID NOT NULL REFERENCES stock_transfers(id) ON DELETE RESTRICT, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, source_zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE RESTRICT, destination_zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE RESTRICT, requested_quantity NUMERIC(18,3) NOT NULL CHECK(requested_quantity > 0), approved_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(approved_quantity >= 0), picked_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(picked_quantity >= 0), dispatched_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(dispatched_quantity >= 0), received_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(received_quantity >= 0), damaged_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(damaged_quantity >= 0), short_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(short_quantity >= 0), remarks TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(stock_transfer_id,product_id,source_zone_id,destination_zone_id));

CREATE TABLE stock_counts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), count_number VARCHAR(50) NOT NULL UNIQUE, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, zone_id UUID REFERENCES warehouse_zones(id) ON DELETE RESTRICT, status VARCHAR(25) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','COUNTING','UNDER_REVIEW','APPROVED','REJECTED','ADJUSTED')), created_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, started_at TIMESTAMPTZ, submitted_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE stock_count_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), stock_count_id UUID NOT NULL REFERENCES stock_counts(id) ON DELETE RESTRICT, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE RESTRICT, system_on_hand_quantity NUMERIC(18,3) NOT NULL CHECK(system_on_hand_quantity >= 0), system_damaged_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(system_damaged_quantity >= 0), physical_quantity NUMERIC(18,3), variance_quantity NUMERIC(18,3) GENERATED ALWAYS AS (CASE WHEN physical_quantity IS NULL THEN NULL ELSE physical_quantity-system_on_hand_quantity END) STORED, status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','COUNTED','VERIFIED','EXCLUDED')), counted_by UUID REFERENCES users(id) ON DELETE RESTRICT, counted_at TIMESTAMPTZ, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(stock_count_id,product_id,zone_id));
CREATE TABLE reconciliations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), reconciliation_number VARCHAR(50) NOT NULL UNIQUE, stock_count_id UUID NOT NULL UNIQUE REFERENCES stock_counts(id) ON DELETE RESTRICT, status VARCHAR(25) NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','UNDER_REVIEW','APPROVED','REJECTED','ADJUSTED')), reviewed_by UUID REFERENCES users(id) ON DELETE RESTRICT, approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, reviewed_at TIMESTAMPTZ, approved_at TIMESTAMPTZ, remarks TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE reconciliation_items (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), reconciliation_id UUID NOT NULL REFERENCES reconciliations(id) ON DELETE RESTRICT, stock_count_item_id UUID NOT NULL REFERENCES stock_count_items(id) ON DELETE RESTRICT, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, system_quantity NUMERIC(18,3) NOT NULL CHECK(system_quantity >= 0), physical_quantity NUMERIC(18,3) NOT NULL CHECK(physical_quantity >= 0), variance_quantity NUMERIC(18,3) NOT NULL, variance_percentage NUMERIC(12,4), unit_cost_snapshot NUMERIC(19,4) NOT NULL CHECK(unit_cost_snapshot >= 0), system_value NUMERIC(19,4) NOT NULL, physical_value NUMERIC(19,4) NOT NULL, value_difference NUMERIC(19,4) NOT NULL, reason_code VARCHAR(50), reason_description TEXT, status VARCHAR(25) NOT NULL DEFAULT 'UNDER_REVIEW' CHECK(status IN ('UNDER_REVIEW','APPROVED','REJECTED','ADJUSTED')), reviewer_note TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(reconciliation_id,stock_count_item_id));
CREATE TABLE inventory_adjustments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), adjustment_number VARCHAR(50) NOT NULL UNIQUE, reconciliation_item_id UUID UNIQUE REFERENCES reconciliation_items(id) ON DELETE RESTRICT, warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE RESTRICT, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, adjustment_type VARCHAR(30) NOT NULL CHECK(adjustment_type IN ('RECONCILIATION','DAMAGE','LOSS','EXPIRY','MANUAL')), status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED','APPLIED','CANCELLED')), quantity_delta NUMERIC(18,3) NOT NULL CHECK(quantity_delta <> 0), previous_on_hand_quantity NUMERIC(18,3) NOT NULL CHECK(previous_on_hand_quantity >= 0), resulting_on_hand_quantity NUMERIC(18,3), reason TEXT NOT NULL, requested_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, approved_by UUID REFERENCES users(id) ON DELETE RESTRICT, applied_by UUID REFERENCES users(id) ON DELETE RESTRICT, requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, approved_at TIMESTAMPTZ, applied_at TIMESTAMPTZ, correlation_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE inventory_transactions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), warehouse_id UUID NOT NULL REFERENCES warehouses(id) ON DELETE RESTRICT, zone_id UUID NOT NULL REFERENCES warehouse_zones(id) ON DELETE RESTRICT, product_id UUID NOT NULL REFERENCES products(id) ON DELETE RESTRICT, transaction_type VARCHAR(30) NOT NULL CHECK(transaction_type IN ('STOCK_IN','STOCK_OUT','TRANSFER_RESERVE','TRANSFER_RELEASE','TRANSFER_OUT','TRANSFER_IN','ADJUSTMENT_IN','ADJUSTMENT_OUT','DAMAGE','LOSS','EXPIRY','RETURN_IN','RETURN_OUT')), quantity_delta NUMERIC(18,3) NOT NULL CHECK(quantity_delta <> 0), previous_on_hand_quantity NUMERIC(18,3) NOT NULL CHECK(previous_on_hand_quantity >= 0), resulting_on_hand_quantity NUMERIC(18,3) NOT NULL CHECK(resulting_on_hand_quantity >= 0), previous_reserved_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(previous_reserved_quantity >= 0), resulting_reserved_quantity NUMERIC(18,3) NOT NULL DEFAULT 0 CHECK(resulting_reserved_quantity >= 0), reference_type VARCHAR(50), reference_id UUID, reason TEXT, performed_by UUID REFERENCES users(id) ON DELETE RESTRICT, correlation_id UUID, occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), recipient_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT, notification_type VARCHAR(40) NOT NULL, severity VARCHAR(15) NOT NULL CHECK(severity IN ('INFO','SUCCESS','WARNING','CRITICAL')), title VARCHAR(200) NOT NULL, message TEXT NOT NULL, related_entity_type VARCHAR(60), related_entity_id UUID, is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, read_at TIMESTAMPTZ);
CREATE TABLE audit_logs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), actor_user_id UUID REFERENCES users(id) ON DELETE SET NULL, action VARCHAR(100) NOT NULL, entity_type VARCHAR(80) NOT NULL, entity_id UUID, previous_state JSONB, new_state JSONB, reason TEXT, correlation_id UUID, ip_address INET, user_agent TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE INDEX ix_inventory_wh_product ON inventory(warehouse_id,product_id);
CREATE INDEX ix_inventory_product_available ON inventory(product_id,available_quantity);
CREATE INDEX ix_inventory_transactions_wh_occurred ON inventory_transactions(warehouse_id,occurred_at DESC);
CREATE INDEX ix_inventory_transactions_product_occurred ON inventory_transactions(product_id,occurred_at DESC);
CREATE INDEX ix_stock_transfers_status_created ON stock_transfers(status,created_at DESC);
CREATE INDEX ix_stock_counts_status_created ON stock_counts(status,created_at DESC);
CREATE INDEX ix_reconciliations_status_created ON reconciliations(status,created_at DESC);
CREATE INDEX ix_notifications_recipient_unread ON notifications(recipient_user_id,is_read,created_at DESC);
CREATE INDEX ix_audit_entity ON audit_logs(entity_type,entity_id,created_at DESC);
CREATE INDEX ix_audit_actor ON audit_logs(actor_user_id,created_at DESC);
