INSERT INTO roles (code, name, description) VALUES
('ADMIN','Administrator','Full administrative access'),('INVENTORY_MANAGER','Inventory Manager','Manages inventory, products and transfers'),('WAREHOUSE_MANAGER','Warehouse Manager','Manages assigned warehouses'),('WAREHOUSE_OPERATOR','Warehouse Operator','Operates assigned warehouses'),('AUDITOR','Auditor','Reviews audit and reconciliation records'),('VIEWER','Viewer','Read-only operational access') ON CONFLICT (code) DO NOTHING;
INSERT INTO permissions (code,name,module,description) VALUES
('USER_READ','Read users','USER','View user profiles'),('USER_CREATE','Create users','USER','Create users'),('USER_UPDATE','Update users','USER','Update user profiles'),('USER_DEACTIVATE','Deactivate users','USER','Change user status'),('ROLE_READ','Read roles','ROLE','View roles and permissions'),('ROLE_ASSIGN','Assign roles','ROLE','Assign user roles'),
('WAREHOUSE_READ','Read warehouses','WAREHOUSE','View warehouses'),('WAREHOUSE_CREATE','Create warehouses','WAREHOUSE','Create warehouses'),('WAREHOUSE_UPDATE','Update warehouses','WAREHOUSE','Update warehouses'),('PRODUCT_READ','Read products','PRODUCT','View products'),('PRODUCT_CREATE','Create products','PRODUCT','Create products'),('PRODUCT_UPDATE','Update products','PRODUCT','Update products'),('INVENTORY_READ','Read inventory','INVENTORY','View inventory'),('INVENTORY_ADJUST','Adjust inventory','INVENTORY','Adjust inventory'),('TRANSFER_READ','Read transfers','TRANSFER','View transfers'),('TRANSFER_CREATE','Create transfers','TRANSFER','Create transfers'),('TRANSFER_APPROVE','Approve transfers','TRANSFER','Approve transfers'),('TRANSFER_DISPATCH','Dispatch transfers','TRANSFER','Dispatch transfers'),('TRANSFER_RECEIVE','Receive transfers','TRANSFER','Receive transfers'),('RECONCILIATION_READ','Read reconciliations','RECONCILIATION','View reconciliations'),('RECONCILIATION_CREATE','Create reconciliations','RECONCILIATION','Create reconciliations'),('RECONCILIATION_APPROVE','Approve reconciliations','RECONCILIATION','Approve reconciliations'),('AUDIT_READ','Read audit logs','AUDIT','View audit history'),('REPORT_READ','Read reports','REPORT','View reports') ON CONFLICT (code) DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='ADMIN' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('WAREHOUSE_READ','PRODUCT_READ','PRODUCT_CREATE','PRODUCT_UPDATE','INVENTORY_READ','INVENTORY_ADJUST','TRANSFER_READ','TRANSFER_CREATE','TRANSFER_APPROVE','TRANSFER_DISPATCH','TRANSFER_RECEIVE','RECONCILIATION_READ','RECONCILIATION_CREATE','REPORT_READ') WHERE r.code='INVENTORY_MANAGER' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('WAREHOUSE_READ','WAREHOUSE_UPDATE','PRODUCT_READ','INVENTORY_READ','INVENTORY_ADJUST','TRANSFER_READ','TRANSFER_CREATE','TRANSFER_APPROVE','TRANSFER_DISPATCH','TRANSFER_RECEIVE','RECONCILIATION_READ','REPORT_READ') WHERE r.code='WAREHOUSE_MANAGER' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('WAREHOUSE_READ','PRODUCT_READ','INVENTORY_READ','TRANSFER_READ','TRANSFER_CREATE','TRANSFER_DISPATCH','TRANSFER_RECEIVE') WHERE r.code='WAREHOUSE_OPERATOR' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('WAREHOUSE_READ','PRODUCT_READ','INVENTORY_READ','TRANSFER_READ','RECONCILIATION_READ','AUDIT_READ','REPORT_READ') WHERE r.code='AUDITOR' ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN ('WAREHOUSE_READ','PRODUCT_READ','INVENTORY_READ','TRANSFER_READ','RECONCILIATION_READ','REPORT_READ') WHERE r.code='VIEWER' ON CONFLICT DO NOTHING;
