INSERT INTO warehouses (code,name,address_line1,city,state,country,capacity_quantity,status) VALUES
('WH-DEL-001','Delhi Central Warehouse','Okhla Industrial Area','New Delhi','Delhi','India',50000,'ACTIVE'),
('WH-MUM-001','Mumbai Distribution Center','Andheri East','Mumbai','Maharashtra','India',40000,'ACTIVE'),
('WH-HYD-001','Hyderabad Regional Warehouse','HITEC City','Hyderabad','Telangana','India',30000,'ACTIVE') ON CONFLICT (code) DO NOTHING;
INSERT INTO warehouse_zones (warehouse_id,code,name,zone_type,capacity_quantity,status) SELECT id,'Z-STORAGE','General Storage','STORAGE',30000,'ACTIVE' FROM warehouses WHERE code='WH-DEL-001' ON CONFLICT (warehouse_id,code) DO NOTHING;
INSERT INTO warehouse_zones (warehouse_id,code,name,zone_type,capacity_quantity,status) SELECT id,'Z-RECEIVE','Receiving','RECEIVING',10000,'ACTIVE' FROM warehouses WHERE code='WH-DEL-001' ON CONFLICT (warehouse_id,code) DO NOTHING;
INSERT INTO warehouse_zones (warehouse_id,code,name,zone_type,capacity_quantity,status) SELECT id,'Z-STORAGE','General Storage','STORAGE',25000,'ACTIVE' FROM warehouses WHERE code='WH-MUM-001' ON CONFLICT (warehouse_id,code) DO NOTHING;
INSERT INTO warehouse_zones (warehouse_id,code,name,zone_type,capacity_quantity,status) SELECT id,'Z-STORAGE','General Storage','STORAGE',20000,'ACTIVE' FROM warehouses WHERE code='WH-HYD-001' ON CONFLICT (warehouse_id,code) DO NOTHING;
INSERT INTO categories (name,description,status) VALUES ('Electronics','Electronic devices and peripherals','ACTIVE'),('Office Supplies','General workplace supplies','ACTIVE'),('Networking','Network infrastructure products','ACTIVE'),('Accessories','Supporting product accessories','ACTIVE') ON CONFLICT DO NOTHING;
INSERT INTO suppliers (code,name,contact_name,email,phone,city,state,country,status) VALUES ('SUP-TECH-001','TechSource India','Sales Desk','sales@techsource.example','+91-11-55501001','New Delhi','Delhi','India','ACTIVE'),('SUP-OFF-001','OfficeMart Supply','Sales Desk','sales@officemart.example','+91-22-55501002','Mumbai','Maharashtra','India','ACTIVE'),('SUP-NET-001','NetworkPro Solutions','Sales Desk','sales@networkpro.example','+91-40-55501003','Hyderabad','Telangana','India','ACTIVE') ON CONFLICT (code) DO NOTHING;
