import type {Alert,Inventory,Notification,Page,ReplenishmentRecommendation,Transfer,User,Warehouse,Zone} from './types';
const BASE=import.meta.env.VITE_API_BASE_URL||'http://localhost:8080/api/v1';
type MasterData={id:string;code:string;name:string;status:string;detail?:string;capacity?:number};
const warehouse=(value:MasterData):Warehouse=>({id:value.id,code:value.code,name:value.name,city:value.detail,status:value.status as Warehouse['status'],capacityQuantity:value.capacity??0});
const zone=(value:MasterData):Zone=>({id:value.id,code:value.code,name:value.name,status:value.status as Zone['status'],zoneType:value.detail||'OTHER',capacityQuantity:value.capacity??0});
export async function api<T>(path:string,options:RequestInit={}){const token=localStorage.getItem('accessToken');const response=await fetch(BASE+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||`Request failed (${response.status})`);return body.data as T}
export const auth={login:(email:string,password:string)=>api<{accessToken:string;user:User}>('/auth/login',{method:'POST',body:JSON.stringify({email,password})}),me:()=>api<User>('/auth/me')};
export const warehouseApi={list:()=>api<Page<MasterData>>('/warehouses?page=0&size=100').then(page=>({...page,content:page.content.map(warehouse)})),get:(id:string)=>api<MasterData>(`/warehouses/${id}`).then(warehouse),zones:(id:string)=>api<MasterData[]>(`/warehouses/${id}/zones`).then(values=>values.map(zone))};
export const inventoryApi={list:(warehouseId?:string)=>api<Page<Inventory>>(`/inventory?page=0&size=100${warehouseId?`&warehouseId=${warehouseId}`:''}`),stockIn:(input:{warehouseId:string;zoneId:string;productId:string;quantity:number;reason:string})=>api<Inventory>('/inventory/stock-in',{method:'POST',body:JSON.stringify({...input,referenceType:'MANUAL_ENTRY'})})};
export const alertApi={list:(warehouseId?:string)=>api<Page<Alert>>(`/alerts?status=ACTIVE&page=0&size=100${warehouseId?`&warehouseId=${warehouseId}`:''}`)};
export const transferApi={list:()=>api<Page<Transfer>>('/transfers?page=0&size=50'),create:(input:{sourceWarehouseId:string;destinationWarehouseId:string;items:{productId:string;sourceZoneId:string;destinationZoneId:string;quantity:number}[];reason:string;notes?:string})=>api<Transfer>('/transfers',{method:'POST',body:JSON.stringify(input)}),action:(id:string,action:'approve'|'pick'|'dispatch'|'receive'|'complete'|'cancel')=>api<Transfer>(`/transfers/${id}/${action}`,{method:'POST'})};
export const operationsApi={replenishment:()=>api<ReplenishmentRecommendation[]>('/operations/replenishment-recommendations')};
export const notificationApi={list:()=>api<Page<Notification>>('/notifications?page=0&size=20'),unread:()=>api<number>('/notifications/unread-count')};
